version: '2'
services:
  captagent:
    container_name: captagent
    image: qxip/captagent-docker
    restart: always
    network_mode: host
    environment:
      - TERM=xterm
      - ETHERNET_DEV=any
      - CAPTURE_HOST=localhost
      - CAPTURE_PORT=9060
      - CAPTURE_PASSWORD=myHep
      - RTCP_ENABLE=true
      - RTCP_PORTRANGE=10000-20000
      - LOG_LEVEL=3
      - CAPTURE_ID=1234